### ISSUE TITLE
Jupyter protocol v5.0 support  (from cl-jupyter  was fishbowl-repl)

### ISSUE THREAD

**Issue by fredokun** [robert-dodier/maxima-fishbowl#1]
Hi Robert,
FYI, I decided to spend some time on fishbowl-repl (now cl-jupyter it's more understandable).
The current master branch is (somehow) working with IPython 3.x ...
It is also much easier to install the kernel in Jupyter.    Maybe  maxima-fishbowl could be built atop cl-jupyter.  I could work with you so that cl-jupyter is modular enough.  I think the evaluator should be pluggable (I would like a swank client at some point)  and the display system is already designed for extensibility thanks to CLOS... Plus the asd-part of cl-jupyter could be installable via quicklisp ...  
Anyhow, if you want to create a 3.x branch (I encourage you to do so,  the jupyter framework is more open for external kernels) the changes are not so big (but they were _painful_, this awful zmq-based protocol is hard to make right and difficult to debug) ..

Cheers,
Frederic

**Comment by robert-dodier** [comment]
Hi Frederic,

Thanks for the update. I will take a look at porting Maxima-Fishbowl to
Jupyter at some point. By the way, are there new features of Jupyter which
make it nicer than IPython 2.x?

I am trying to implement colorization via CodeMirror but I am having some
trouble with it. I modified a suitable existing CodeMirror script to make a
highlighting mode for Maxima, but I can't figure out where it is supposed
to go in order to be loaded, and I don't understand how it is executed once
it is loaded. I tried to copy the stuff that you have in fishbowl-repl, but
it doesn't seem to work for me. Do you have any words of wisdom? I am
thinking I should try to get some help from either the CodeMirror forum or
IPython-dev, but I don't have a well-formed question -- just "I can't get
it to work". Thanks in advance for any light you can shed on it.

best,

Robert

PS. I did get highlighting for HTML export to work -- IPython uses Pygments
for that. I copied & modified a pygments file to get a Maxima highlighter,
put it in the pygments directory, ran the script which updates the master
list of available highlighters, and it just works. That's nice.

**Comment by nilqed** [comment]
Hello Robert
The mode goes to somewhere like:
 /usr/local/lib/python2.7/dist-packages/IPython/html/static/components/codemirror/mode/
whereby you probably have to change python2.7 to your python 3 installation (e.g. python3.4). Sometimes you also find 'IPython' in 'site-packages'  instead of 'dist-packages', however, inside the IPython directory the path is fixed (html/static/components/codemirror/mode/). Bill page wrote a mode for SPAD (FriCAS, Axiom ...) for the Sage cloud, so I created a folder 'spad' and put it to the location given above. Voilà, it works fine with Jupyter 3.2 and in older IPython notebooks as well.
Unfortunately you also need a pygments lexer if you want to export the 'mode' to one of the available formats (md,rst,..).
Best regards
Kurt   

p.s.
the 'language' field in the kernel spec must match your mode-name of course.

**Comment by scios** [comment]
Hello Frederic
Many thanks for this master-piece. I was using 'fishbowl' for some time as native FriCAS/Axiom kernel and tried to implement protocol 5 myself, with - needless to say - little success. Now 'cl-jupyter' worked out of the box! 
    One small issue is the following (which is easy to work around manually) compile error.
    
                         FriCAS Computer Algebra System
                             Version: FriCAS 2014-09-10
                     Timestamp: Mit Aug 19 20:50:03 CEST 2015
    -----------------------------------------------------------------------------
       Issue )copyright to view copyright notices.
       Issue )summary for a summary of useful system commands.
       Issue )quit to leave FriCAS and return to shell.
    -----------------------------------------------------------------------------

    To load "cl-jupyter":
     Load 1 ASDF system:
        cl-jupyter
    ; Loading "cl-jupyter"
    .............;
    ; caught ERROR:
    ;   READ error during COMPILE-FILE:
    ;
    ;     Symbol "MAKE-OCTET-VECTOR" not found in the NIBBLES package.
    ;
    ;       Line: 248, Column: 60, File-Position: 13055
    ;
    ;       Stream: #<SB-INT:FORM-TRACKING-STREAM
    ;                 for "file /home/kfp/quicklisp/dists/quicklisp/software/ironcld_0.33.0/src/ciphers/modes.lisp"
    ;                 {1006C4D673}>
    While evaluating the form starting at line 16, column 0

       >> System error:
       COMPILE-FILE-ERROR while
    compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "ciphers" "modes">

      of #P"~/ifricas.lisp":;
                            ; compilation unit aborted
                           ;   caught 3 fatal ERROR conditions
                           ;   caught 1 ERROR condition

I'm using the latest versions of SBCL (1.2.14) and quicklisp. Do you know of any recent changes in 'ironclad'? 
Best regards
Kurt

**Comment by robert-dodier** [comment]
Closing this issue as there has been no discussion for some time. Thanks to my correspondents for their interest.
